---
- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Ensure MariaDB is started and enabled
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Install python3-pymysql for Ansible mysql modules
  apt:
    name: python3-pymysql
    state: present

- name: Create WordPress database
  mysql_db:
    name: wordpress
    state: present


# - name: Secure MariaDB installation
#   ansible.builtin.command: >
#    sudo mysql -u root -e "CREATE DATABASE wordpress;
#    CREATE USER 'wpuser'@'localhost' IDENTIFIED BY 'StrongPassword!';
#    GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'localhost';
#    FLUSH PRIVILEGES;"

    
- name: Create WordPress DB user
  mysql_user:
    name: wp_user
    password: wp_pass
    priv: 'wordpress.*:ALL'
    state: present
